set_humidity:
  name: Set humidity
  description: Set the target humidity of WeMo humidifier devices.
  target:
    entity:
      integration: wemo
      domain: fan
  fields:
    target_humidity:
      name: Target humidity
      description: Target humidity.
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"

reset_filter_life:
  name: Reset filter life
  description: Reset the WeMo Humidifier's filter life to 100%.
  target:
    entity:
      integration: wemo
      domain: fan

set_timer:
  description: Set the target timer of WeMo crockpot devices.
  fields:
    entity_id:
      description: Names of the WeMo Crockpot entities (1 or more entity_ids are required).
      example: "switch.crock_pot_r_slow_cooker_high"
    target_time:
      description: Target time (in minutes). This is a integer value between 0 and 100.
      example: 60